# @package _global_

#### Model params #############################################################
model:
  name: rnn_emb
  hparams:
    hidden_size: 128  # 128, 64, 32
    emb_size: 32  # 32, 16
    add_embedding_before: ['encoding', 'decoding']
    use_local_weights: null # ['encoder', 'decoder']
    time_layers: 2
    activation: 'elu'
    noise_mode: 'lin'